ARDUINO_DIR=/root/.arduino_ide
ARDMK_DIR=/root/.arduino_mk
BOARD_TAG=uno
# MONITOR_PORT=/dev/ttyS3
ARDUINO_PORT=/dev/ttyS3
ARDUINO_LIBS=
AVRDUDE_ARD_PROGRAMMER=arduino
AVRDUDE_ARD_BAUDRATE=9600

include $(ARDMK_DIR)/Arduino.mk
